### PR TITLE
added sidebar menu

### PR DESCRIPTION
**Pull request by 0-mayurkaretha**

### CODE REVIEW

**Comment by 0-mayurkaretha** [comment]
@mohitahlawat2001 please go through PR once.
left inner pages empty for others to contribute.

**Review by mohitahlawat2001 — COMMENTED** [review]
resolve confilt!

**Comment by 0-mayurkaretha** [comment]
> resolve confilt!

resolved in [`bfc5645`](https://github.com/mohitahlawat2001/calculator-app/pull/32/commits/bfc5645ab77e4bf0d4041695ef660966fb63c48e)

**Comment by mohitahlawat2001** [comment]
provide image before and after changes

**Comment by 0-mayurkaretha** [comment]
Here,

pic1
pic1

pic2
pic2

**Comment by mohitahlawat2001** [comment]
resolve conflits again!

Also this sidebar with scientific calculator needs calculator also 
can you try to add,

**Pull request closed without merging**
